TestsProjects
LT-Students/DigitalOffice pull request #10
Opened 2020-07-21 16:06 UTC by DenisKrivoruchko11

Added test projects for each service

2020-07-21 16:37 UTC, KostinP approved these changes

2020-07-21 17:54 UTC, DarkFelas requested changes

2020-07-21 17:54 UTC, DarkFelas commented on DigitalOffice/DigitalOffice.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "CheckRightsServiceTests", "Tests\CheckRightsServiceTests\CheckRightsServiceTests.csproj", "{B1995E22-8ED7-4C89-97CE-B062533E5BE8}"
All projects have wrong name, read task again.

2020-07-21 20:03 UTC, DenisKrivoruchko11 commented on DigitalOffice/DigitalOffice.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "CheckRightsServiceTests", "Tests\CheckRightsServiceTests\CheckRightsServiceTests.csproj", "{B1995E22-8ED7-4C89-97CE-B062533E5BE8}"
fixed

2020-07-21 20:53 UTC, lalagvana approved these changes

2020-07-21 23:02 UTC, DarkFelas requested changes

2020-07-21 23:02 UTC, DarkFelas commented on DigitalOffice/Tests/CheckRightsServiceTests/UnitTest1.cs
> +namespace CheckRightsServiceTests
Fix namespaces for all projects

2020-07-22 08:59 UTC, DenisKrivoruchko11 commented on DigitalOffice/Tests/CheckRightsServiceTests/UnitTest1.cs
> +namespace CheckRightsServiceTests
fixed

2020-07-22 09:00 UTC, DarkFelas approved these changes

2020-07-22 10:22 UTC, Inzilbeth approved these changes

2020-07-22 12:03 UTC, mekk1t approved these changes

2020-07-22 13:13 UTC, merged