CheckRightsService_AddRightsToDbMigration
LT-Students/DigitalOffice pull request #31
Opened 2020-08-02 10:34 UTC by mekk1t

Inserted basic values to database via DbRight configuration class.
Fluent API + .HasData() -> dotnet ef migrations add -> dotnet ef database update

2020-08-02 10:51 UTC, KostinP requested changes

2020-08-02 10:51 UTC, KostinP commented on DigitalOffice/Services/CheckRightsService/Database/Entities/DbRight.cs
> +                    Name = "Add/Edit/Remove project",
Hmm, I don't think that one is right.

2020-08-02 10:51 UTC, KostinP commented on DigitalOffice/Services/CheckRightsService/Database/Entities/DbRight.cs
> +                    Name = "Add/Edit/Remove user",
Hmm, I don't think that one is right.

2020-08-02 10:57 UTC, KostinP commented on DigitalOffice/Services/CheckRightsService/Database/Entities/DbRight.cs
> +                    Name = "Add/Edit/Remove project",
Perhaps another problem is in the name. You can have the right to edit any projects, you can have the right to edit your projects.

2020-08-02 11:18 UTC, mekk1t commented on DigitalOffice/Services/CheckRightsService/Database/Entities/DbRight.cs
> +                    Name = "Add/Edit/Remove project",
I agree, i requested clarificafion from Spartak.
Trello task description states that info, everything in one right.
That also made me think about right types, like, do we need it at all? 
If yes, how we're using it?

2020-08-02 12:04 UTC, lalagvana approved these changes

2020-08-02 12:05 UTC, lalagvana commented on DigitalOffice/Services/CheckRightsService/Database/Entities/DbRight.cs
> +                    Name = "Add/Edit/Remove project",
IMHO in our current model of this service we don't need right types.

2020-08-02 12:07 UTC, lalagvana commented on DigitalOffice/Services/CheckRightsService/Database/Entities/DbRight.cs
> +                    Name = "Add/Edit/Remove project",
Cause now these rights don't relate with specific project/user etc.

2020-08-02 20:37 UTC, mekk1t commented
![image](https://user-images.githubusercontent.com/61093487/89131931-1ca9a500-d519-11ea-858d-5436cdd1ec54.png)
Migration successfully applied

2020-08-04 21:54 UTC, djino97 commented on DigitalOffice/Services/CheckRightsService/Database/Entities/DbRight.cs
> +                    Name = "Add/Edit/Remove project",
UnlessIs this should not be all data entered by users (admin) themselves?

2020-08-04 22:02 UTC, djino97 commented on DigitalOffice/Services/CheckRightsService/Database/Entities/DbRight.cs
> +                    Name = "Add/Edit/Remove project",
Сan be done multiple rights with one id for one user. Сan be done one right for one user, but with two different id assigned to the one user

2020-08-05 05:10 UTC, KostinP commented on DigitalOffice/Services/CheckRightsService/Database/Entities/DbRight.cs
> +                    Name = "Add/Edit/Remove project",
> @KostinP Сan be done multiple rights with one id for one user. Сan be done one right for one user, but with two different id assigned to the one user

I do not argue with this, the question was about something else. I may not understand you.

2020-08-05 07:06 UTC, KostinP approved these changes

2020-08-05 12:31 UTC, djino97 approved these changes

2020-08-06 08:00 UTC, ifelseelif approved these changes

2020-08-06 15:33 UTC, MihailKulikov approved these changes

2020-08-07 12:54 UTC, merged