AuthenticationService_CheckToken
LT-Students/DigitalOffice pull request #59
Opened 2020-08-16 22:16 UTC by djino97

- Added user jwt validation logic for check token.
- Added command pattern ValidationUserJwtCommand.
- Added consumer for read from broker queue UserJwtConsumer.
- At the moment unit-test are not added, but it will added soon.

2020-08-16 23:37 UTC, KostinP requested changes

2020-08-16 23:37 UTC, KostinP commented on DigitalOffice/Services/AuthenticationService/Broker/Senders/Interface/ISender.cs
> +        /// <param name="item">It is message context</param>
Some of the commentators moved out. Somewhere there are not enough dots, for convenience I will highlight them with a word here

2020-08-16 23:37 UTC, KostinP commented on DigitalOffice/Services/AuthenticationService/Commands/Interfaces/IUserLoginCommand.cs
> +        ///Method for getting user id and jwt by email and password
Here.

2020-08-16 23:37 UTC, KostinP commented on DigitalOffice/Services/AuthenticationService/Commands/Interfaces/IValidationUserJwtCommand.cs
> +        ///Execute call method for validate user token
Here.

2020-08-16 23:37 UTC, KostinP commented on DigitalOffice/Services/AuthenticationService/Token/Interfaces/IJwtSigningDecodingKey.cs
> +        ///Method for getting decoding key jwt
Here.

2020-08-16 23:37 UTC, KostinP commented on DigitalOffice/Services/AuthenticationService/Token/Interfaces/IJwtSigningEncodingKey.cs
> +        ///Method for getting encoding key jwt
Here.

2020-08-16 23:37 UTC, KostinP commented on DigitalOffice/Tests/AuthenticationServiceTests/Controllers/AuthenticationControllerTests.cs
> +﻿
Extra empty lines.

2020-08-16 23:37 UTC, KostinP commented on DigitalOffice/Tests/UserServiceTests/Broker/Consumer/UserConsumerTests.cs
> +
Extra empty line.

2020-08-16 23:37 UTC, KostinP commented on DigitalOffice/Tests/UserServiceTests/Repositories/UserRepositoryTests.cs
> +        public void FailShouldThrowExceptionIfUserWithRequiredIdDoesNotExist()
These are unnecessary changes. Conflicts need to be resolved.

2020-08-16 23:39 UTC, KostinP commented
How is this branch related to this branch? https://github.com/LT-Students/DigitalOffice/pull/32/files

2020-08-17 13:15 UTC, denis-kriv commented on DigitalOffice/Services/AuthenticationService/Startup.cs
> +        private void ConfigJwt(IServiceCollection services)
Maybe `ConfigureJwt` ? It is not critical, but I think it is better.

2020-08-17 13:15 UTC, denis-kriv commented on DigitalOffice/Services/AuthenticationService/Startup.cs
> +        private void ConfigRabbitMq(IServiceCollection services)
And here.

2020-08-17 13:15 UTC, denis-kriv commented on DigitalOffice/Services/AuthenticationService/Startup.cs
> +        private void ConfigBrokerSenders(IServiceCollection services)
And Here.

2020-08-17 13:15 UTC, denis-kriv commented on DigitalOffice/Services/AuthenticationService/Startup.cs
> +        private void ConfigCommands(IServiceCollection services)
And Here.

2020-08-17 13:15 UTC, denis-kriv commented on DigitalOffice/Services/AuthenticationService/Startup.cs
> +        private void ConfigValidators(IServiceCollection services)
And Here.

2020-08-17 13:15 UTC, denis-kriv commented on DigitalOffice/Services/AuthenticationService/Token/NewToken.cs
> +                    claims: claims,     // Contains information of user email
May be it will be better if you delete this comment.

2020-08-17 13:15 UTC, denis-kriv commented on DigitalOffice/Services/AuthenticationService/Token/SigningSymmetricKey.cs
> +        const string SIGNING_SECURITY_KEY = "qyfi0sjv1f3uiwkyflnwfvr7thpzxdxygt8t9xbhielymv20";
I am not sure, that we can place secutity key in public repository.

2020-08-17 13:15 UTC, denis-kriv commented on DigitalOffice/Services/AuthenticationService/Validators/UserLoginValidator.cs
> +        }
May be we need more validation rules.

2020-08-17 13:15 UTC, denis-kriv commented on DigitalOffice/Services/UserService/Repositories/Interfaces/IUserRepository.cs
> +        DbUser GetUserByEmail(string userEmail);
Documentation

2020-08-17 13:15 UTC, denis-kriv commented on DigitalOffice/Services/UserService/Repositories/UserRepository.cs
> +            DbUser user = userServiceDbContext.Users.FirstOrDefault(u => u.Email == userEmail);
I think that we can use `Find` here

2020-08-17 13:15 UTC, denis-kriv commented on DigitalOffice/Services/UserService/Repositories/UserRepository.cs
> +            DbUser user = userServiceDbContext.Users.FirstOrDefault(u => u.Email == userEmail);
And why not to use `var`

2020-08-17 13:15 UTC, denis-kriv commented on DigitalOffice/Services/UserService/Startup.cs
> +            ConfigRabbitMq(services);
"Configure..."

2020-08-17 13:15 UTC, DenisKrivoruchko11 commented on DigitalOffice/Tests/AuthenticationServiceTests/Broker/Sender/AuthenticationSenderTests.cs
> +    }
Looks strange

2020-08-17 13:15 UTC, DenisKrivoruchko11 commented on DigitalOffice/Tests/AuthenticationServiceTests/Commands/UserLoginCommandTests.cs
> +        public void BrokerSetUp()
`private` ?

2020-08-17 13:15 UTC, DenisKrivoruchko11 commented on DigitalOffice/Tests/AuthenticationServiceTests/Validators/UserLoginValidatorTests.cs
> +            validator.ShouldNotHaveValidationErrorFor(x => x.Password, "Example");
Why do we have password field here? I think that we can check one field in one test.

2020-08-17 13:41 UTC, closed without merging